name: write-model-result
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: detection-results
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: Host address for the InfluxDB instance.
    defaultValue: eu-central-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_TOKEN
    inputType: FreeText
    description: Authentication token to access InfluxDB.
    defaultValue: 2G8HlAYgKZKRsYZDtITTZRwfmvK9ITVyp6JDelIwik8wfOCLq1U_ltKJ_lsqAiis2owE4M8YaPL5M6g7kPfYiQ==
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: Organization name in InfluxDB.
    defaultValue: 6a841c0c08328fb1
    required: false
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: quix
    required: true
  - name: INFLUXDB_TAG_COLUMNS
    inputType: FreeText
    description: Columns to be used as tags when writing data to InfluxDB.
    defaultValue: "['machineID']"
    required: false
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: The InfluxDB measurement to write data to. If not specified, the name of the input topic will be used
    defaultValue: mlresult
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
