name: MQTT
language: python
variables:
  - name: topic
    inputType: OutputTopic
    description: Name of the output topic to publish to.
    defaultValue: rawdata
    required: true
  - name: mqtt_topic
    inputType: FreeText
    description: The root for messages in MQTT, this can be anything
    defaultValue: machine/#
    required: true
  - name: mqtt_server
    inputType: FreeText
    description: The address of your MQTT server
    defaultValue: broker.hivemq.com
    required: true
  - name: mqtt_port
    inputType: FreeText
    description: The port of your MQTT instance
    defaultValue: 1883
    required: true
  - name: mqtt_username
    inputType: FreeText
    description: Your MQTT username
    required: true
  - name: mqtt_password
    inputType: HiddenText
    description: Your MQTT password
    required: true
  - name: mqtt_version
    inputType: FreeText
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
